name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '21 11 * * 5'

jobs:

  linux:
    name: Linux build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update
      run: sudo apt-get update

    - name: Dependencies
      run: sudo apt-get install build-essential cmake libboost-all-dev liblzma-dev

    - name: Configure
      run: cmake --version && cmake -B ${{github.workspace}}/build -Werror=dev -Werror=deprecated -DCONTINUOUS_INTEGRATION=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Check Style
      run: cmake --build ${{github.workspace}}/build --target style

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/build/innoextract
        asset_name: innoextract
        tag: ${{ github.ref }}
        overwrite: true
        body: "Add binaries"

  macos:
    name: macOS build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update
      run: brew update

    - name: Workaround for Python install issues - https://github.com/actions/runner-images/issues/8838
      run: brew install python@3 || brew link --overwrite python@3

    - name: Dependencies
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: brew install boost xz

    - name: Configure
      run: cmake --version && cmake -B ${{github.workspace}}/build -Werror=dev -Werror=deprecated -DCONTINUOUS_INTEGRATION=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  windows:
    name: Windows build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Boost with Chocolatey
      run: choco install boost-msvc-14.3 -y --version 1.87.0
    
    - name: Install LZMA
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://github.com/ShiftMediaProject/liblzma/releases/download/v5.6.3/liblzma_v5.6.3_msvc17.zip" -OutFile lzma.zip
        Expand-Archive -Path lzma.zip -DestinationPath "D:\lzma_5_6_3"
    
    - name: Configure
      run: cmake --version && cmake -B ${{github.workspace}}\build -Werror=dev -Werror=deprecated -DCONTINUOUS_INTEGRATION=1 -DLZMA_LIBRARY=D:\lzma_5_6_3\lib\x64\liblzma.lib -DLZMA_INCLUDE_DIR=D:\lzma_5_6_3\include
      env:
        Boost_DIR: C:\local\boost_1_87_0\lib64-msvc-14.3\cmake\Boost-1.87.0

    - name: Build
      run: cmake --build ${{github.workspace}}\build

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/build/Debug/innoextract.exe
        asset_name: innoextract.exe
        tag: ${{ github.ref }}
        overwrite: true
        body: "Add binaries"
